// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://decaqqymeejyvnjtfkby.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRlY2FxcXltZWVqeXZuanRma2J5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMDE4OTQsImV4cCI6MjA2OTY3Nzg5NH0.teOx3uBdwpNgX3Ev87B5Ima_9_42ocELnAph6YvhzEs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});